[profile.default]
src = "src"
out = "abi"
libs = ["lib"]
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink=lib/chainlink",
    "@morpho=lib/morpho-blue/src"
]
fs_permissions = [{ access = "write", path = "../" }]
solc_version = "0.8.30"
gas_reports = ["*"]
ffi = true
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
